accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'

urlpatterns = [
    url(r'^registration/$', views.create_user_form, name='registration'),
    url(r'^$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^point/$', views.point_crown, name='point_crown'),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),

]

meex/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('tip.urls', namespace='tips')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tip/urls.py
from django.conf.urls import url
from tip import views


app_name = 'tips'

urlpatterns = [
    url(r'^$', views.tips_list_search, name='list'),
    url(r'^create_tip/$', views.crate_tip, name='create_tip'),
    url(r'^reglas/$', views.reglas_view, name='reglas'),
    url('thankyou/', views.request_services, name='gracias'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserTips.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),

    # url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^tip/(?P<pk>\d+)/edit/$', views.TipUpdateView.as_view(), name='tip_edit'),
    url(r'^tip/(?P<pk>\d+)/remove/$', views.TipDeleteView.as_view(), name='tip_remove'),

    url(r'^tip/(?P<pk>\d+)$', views.tip_details, name='tip_detail'),
    url(r'^like/$', views.like_tip, name='like_tip'),
    url(r'^down/$', views.down_tip, name='down_tip'),
    url(r'^warning', views.CreateProfileBeforeSearch.as_view(), name='createprofilebeforeview'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

MY_CHOICES = (
    ('mujer', 'mujer'),
    ('hombre', 'hombre')
)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profiles', on_delete=models.CASCADE)
    gender = models.CharField(max_length=7, choices=MY_CHOICES)
    description = models.TextField(max_length=200)
    profile_pic = models.ImageField(upload_to='media', blank=True)
    rey_reina = models.BooleanField(default=False)
    points = models.ManyToManyField('auth.User', related_name='puntos', blank=True, through='PointsUserList')
    blocked_users = models.ManyToManyField('auth.User', related_name='blocked', blank=True, through='BlockedList')

    def __str__(self):
        return self.user.username

    def total_points(self):
        return self.points.count()

    def get_absolute_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.pk})


class PointsUserList(models.Model):
    profile = models.ForeignKey(Profile, related_name='admiradores', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class BlockedList(models.Model):
    profile = models.ForeignKey(Profile, related_name='members', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea, TextInput


class UserFormRegistration(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserFormProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('gender', 'description', 'profile_pic')

        widgets = {
            'description': TextInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].label = "Descripción"
        self.fields['profile_pic'].label = "Foto de perfil"


# -------------------------to update---------------------------------------

class UserFormProfileUpdate(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'profile_pic']

        widgets = {
            'description': Textarea(attrs={'class': 'form-control'}),
        }


class UserFormCreationFormUpdate(forms.ModelForm):
    User._meta.get_field('email')._unique = True
    User._meta.get_field('username')._unique = True

    class Meta:
        model = User
        fields = ('username',)

        widgets = {
            'username': TextInput(attrs={'class': 'form-control'})
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from tip.models import MakeTip
from .forms import UserFormRegistration, UserFormProfile, UserFormCreationFormUpdate, UserFormProfileUpdate
from accounts.models import Profile, PointsUserList, BlockedList
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings


class ViewUserProfile(TemplateView, LoginRequiredMixin):
    template_name = 'accounts/profile.html'


@login_required
def crate_user_profile(request):
    form = UserFormProfile()

    if request.method == "POST":
        form = UserFormProfile(data=request.POST, files=request.FILES)

        if form.is_valid():
            userprofile = form.save(commit=False)

            pic = form.cleaned_data['profile_pic']
            if not pic:
                userprofile.profile_pic = 'hummingbird.jpg'
            userprofile.user = request.user

            form.save(commit=True)

            return render(request, 'tip/tip_list.html')
        else:
            form = UserFormProfile()

    return render(request, 'accounts/profile.html', {'form': form})


def create_user_form(request):
    form = UserFormRegistration()

    if request.method == "POST":
        form = UserFormRegistration(request.POST)

        if form.is_valid():
            form.save(commit=False)
            email_user = form.cleaned_data['email']
            username = form.cleaned_data['username'].lower()
            form.username = username
            contra = form.cleaned_data['password1']
            form.save(commit=True)

            msg_contra = username + contra + email_user

            msg_html = render_to_string('registration/welcome.html')
            send_mail('C2020T', 'Bienvenido!', settings.EMAIL_HOST_USER, ['silvanovaldez90@yahoo.com'], html_message=msg_contra,
                      fail_silently=False)
            return redirect('login')
        else:
            form = UserFormRegistration()

    return render(request, 'registration/form.html', {'form': form})


@login_required
def search_users(request):
    queryset_list = {}

    query = request.GET.get('q')
    if query is not None:
        queryset_list = Profile.objects.all().exclude(user=request.user)
        queryset_list = queryset_list.filter(
            Q(user__first_name=query) | Q(user__username=query) | Q(user__last_name=query) | Q(user__email=query))

    context = {
        "object_list": queryset_list
    }
    return render(request, 'search_users/index.html', context)


@login_required
def user_detail_view(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    is_admirador = False
    is_blocked = False

    if BlockedList.objects.filter(user=profile.user, profile=request.user.profiles):
        is_blocked = True

    if PointsUserList.objects.filter(user=request.user, profile=profile.pk):
        is_admirador = True

    context = {
        'is_blocked': is_blocked,
        'is_admirador': is_admirador,
        'user_list': profile,
        'post_list': MakeTip.objects.filter(author=profile.user),
    }
    return render(request, 'accounts/user_detail.html', context)


@login_required
def point_crown(request):
    is_admirador = False
    profile = get_object_or_404(Profile, id=request.POST.get('profile_pk'))
    membership = PointsUserList.objects.filter(user=request.user, profile=profile.pk)
    if membership:
        membership.delete()
        is_admirador = False

    else:
        PointsUserList.objects.create(user=request.user, profile=profile)
        is_admirador = True
    return redirect(profile.get_absolute_url())


@login_required
def edit_profile(request):
    image = request.user.profiles.profile_pic

    if request.method == 'POST':
        form1 = UserFormCreationFormUpdate(request.POST, instance=request.user)
        form2 = UserFormProfileUpdate(request.POST, request.FILES, instance=request.user.profiles)

        if form1.is_valid() and form2.is_valid():
            form1.save(commit=True)
            form2.save(commit=True)
            return redirect('tips:list')
    else:
        form1 = UserFormCreationFormUpdate(instance=request.user)
        form2 = UserFormProfileUpdate(instance=request.user.profiles)

    return render(request, 'accounts/createprofile.html', {'form': form1, 'formm': form2, 'image': image})


class UserProfileView(TemplateView, LoginRequiredMixin):
    template_name = 'accounts/view_profile.html'


class ConfirmDeactivate(TemplateView, LoginRequiredMixin):
    template_name = 'profile/confirm_deactivate.html'


@login_required
def delete_profile(request):
    user = request.user
    user.is_active = False
    user.save()
    messages.success(request, 'Perfil fue desactivado.')
    return redirect('tips:list')

accounts/templates/accounts/createprofile.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% load bootstrap4 %}

{% block serach_block %}
{% endblock %}

{% block body_block %}
<div class="jumbotron main_wrapper_jumbotron">
    <div class="container">
    <div class="jumbotron">
        <div align="center">
            <p>Editar Perfil</p>
        </div>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-12">
                    <label for="inputEmail4">Username</label>
                    <p>{{ form.username }}</p>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <label for="Texto">Descripcion</label>
                    <p>{{ formm.description }}</p>
                </div>

            </div>
            <div class="form-row">
                <div class="form-group col-lg-6 col-md-6 col-sm-12">
                    <img src="{{ image.url }}" class="silvano" style="max-height: 280px; width:100%;max-width:268px; object-fit: cover">
                    <p accept="image/*" onchange="loadFile(event)">{{ formm.profile_pic }}</p>
                </div>


                <div class="form-group col-lg-6 col-md-6 col-sm-12">
                    <img id="output" style="max-height: 280px; width:100%;max-width:268px; object-fit: cover"/>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Crear</button>
        </form>
    </div>

</div>
</div>


<script>
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>




{% endblock %}

accounts/templates/accounts/password_reset.html
<!DOCTYPE html>
{% extends "main.html" %}
{% block body_block %}

<div class="container">
<div class="jumbotron">
    <div align="center">



        <form method="POST">
            {% csrf_token %}
                <legend class="border-bottom mb-4">Crear nueva contraseña</legend>
                {{ form }}
                <button class="btn btn-outline-info" type="submit">Requerir una nueva contraseña</button>
        </form>

        </div>
</div>
</div>
{% endblock body_block %}

accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
{% extends "main.html" %}
{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <p>Tu contraseña ah sido reiniciada.</p>
                <a href="{% url 'login' %}">Iniciar Sesión aqui</a>
            </div>
        </div>
    </div>

{% endblock body_block %}

accounts/templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
{% extends "main.html" %}
{% block body_block %}
        <form method="POST">
            {% csrf_token %}
                <legend class="border-bottom mb-4">Reiniciar contraseña</legend>
                {{ form }}
                <button class="btn btn-outline-info" type="submit">Reiniciar contraseña</button>
        </form>
{% endblock body_block %}

accounts/templates/accounts/password_reset_done.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block body_block %}
    <div class="container">
                <div class="jumbotron">
                    <div align="center">
                        <p>Un email ah sido enviado con instruciones para Reiniciar tu contraseña</p>
                    </div>
                </div>
            </div>

{% endblock body_block %}

accounts/templates/accounts/profile.html
<!DOCTYPE html>
{% extends 'main.html'%}
{% load bootstrap4 %}

{% block serach_block %}
{% endblock %}

{% block body_block %}
<div class="jumbotron main_wrapper_jumbotron">
    <div class="container">
    <div class="jumbotron">
        <h3 align="center">Crear Perfil</h3>

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-4 col-sm-12">
                <label>Descripcion</label>
            {{ form.description }}
            </div>

            <div class="form-group col-md-4 col-sm-12">
                <label>Imagen</label>
                <p accept="image/*" onchange="loadFile(event)">{{ form.profile_pic }}</p>
            </div>

                <div class="form-group col-md-4 col-sm-12">
                    <img id="output" style="width: 170px; height: 200px; object-fit: cover"/>
                </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6 col-sm-12">
                <label>Género
                {{ form.gender }}</label>

        </div>
        </div>


    <input type="submit" value="Crear">
    </form>
        </div>
</div>

</div>
<script>
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
</script>


{% endblock %}

accounts/templates/accounts/user_detail.html
<!DOCTYPE html>
{% extends 'main.html' %}

{% block serach_block %}
{% endblock %}

{% block body_block%}
    <div class="jumbotron main_wrapper_jumbotron">
        <div class="container">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
              </div>
            {% endfor %}

            <div class="d-flex justify-content-center">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    {% if user_list.profile_pic %}
                        <img class="card-img-top silvano" src="{{ user_list.profile_pic.url }}" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">username: {{ user_list.user.username }}</p>
                        <p class="card-text">descripcion: {{ user_list.description }}</p>
                        <div align="left">
                            {% if request.user in user_list.blocked_users.all or user_list.user in request.user.profiles.blocked_users.all%}
                                <p>No puedes mensajear oh agregar como amigo</p>
                            {% else %}
                                <a href="{% url 'message:add_message' pk=user_list.pk %}" class="btn btn-outline-primary btn-sm">Mensajear</a>
                                <br>
                                <br>

                                <form method="POST" action="{% url 'friends:add_friend' pk=user_list.pk %}">
                                    {% csrf_token %}
                                    {{ form }}
                                    <input class="btn btn-outline-success btn-sm" type="submit" value="Agregar amigo">
                                </form>
                            {% endif %}

                            <form method="POST" action="{% url 'message:block_user' %}">
                                {% csrf_token %}
                                {% if is_blocked %}
                                    <button type="submit" class="btn btn-light btn-sm" name="post_id" value="{{ user_list.pk }}">Desbloquear</button>
                                {% else %}
                                    <br>
                                    <button type="submit" class="btn btn-outline-danger btn-sm" name="post_id" value="{{ user_list.pk }}">Bloquear</button>
                                {% endif %}
                            </form>
                        </div>
                        {% if user_list.gender == 'mujer' %}

                            <div class="dropdown-divider"></div>

                            <form method="POST" class="post-form" action="{% url 'accounts:point_crown'%}">
                                {% csrf_token %}
                                {% if is_admirador %}
                                    <p>Quitar el punto para Corona?</p>
                                    <button type="submit" class="btn btn-dark" name="profile_pk" value="{{ user_list.pk }}"><img src="http://drive.google.com/uc?export=view&id=1DP9VdMF3iIyDNubJOyLiWW9zKWxZrIkt" width="40" height="40"></button>
                                    <p>{{ user_list.points.count }}/69</p>
                                {% else %}
                                    <p>Dar punto para corona</p>
                                    <button type="submit" class="btn btn-dark" name="profile_pk" value="{{ user_list.pk }}"><img src="http://drive.google.com/uc?export=view&id=16fqZqtD6u2jLeRQYVk7cj_APWgNGMezU" width="40" height="40"></button>
                                    <p>{{ user_list.points.count }}/69</p>

                                {% endif %}
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <div class="row">

            {% for post in post_list %}

                <div class="col-md-4">
                    <div>
                        <div class="card text-white bg-dark mb-3">
                            {% if post.post_pic %}
                                <img class="card-img-top silvano" src="{{ post.post_pic.url }}" alt="Card image cap">
                                <div class="card-body">
                                    <p class="text-center"><a href="{% url 'tips:tip_detail' pk=post.id %}">{{ post.title }}</a></p>
                                    <p class="card-text"><a href="{% url 'tips:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>
                                </div>
                                <div class="card-footer text-muted">

                                    {{ post.likes.count }} <img src="http://drive.google.com/uc?export=view&id=1iyEMUO63gvEuYu1zLYWi3SpUzCbU6tWs" width="30" height="30" class="penis_icon">
                                    {{ post.down_votes.count }} <img src="http://drive.google.com/uc?export=view&id=1IwWo_KmqZ_DSPiM1hf-7INmrzxl7VNye" width="30" height="30" class="penis_icon">
                                    {{ post.comments.count }} comentario{{ post.comments.count|pluralize }}
                                </div>

                            {% else %}
                                <div class="card-body">
                                    <p class="text-center"><a href="{% url 'tips:tip_detail' pk=post.id %}">{{ post.title }}</a></p>
                                    <p class="card-text">{{ post.post_info_summary }}</p>
                                    <p class="card-text"><a href="{% url 'tips:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>

                                </div>
                                <div class="card-footer text-muted">
                                    {{ post.likes.count }} <img src="http://drive.google.com/uc?export=view&id=1iyEMUO63gvEuYu1zLYWi3SpUzCbU6tWs" width="30" height="30" class="penis_icon">
                                    {{ post.down_votes.count }} <img src="http://drive.google.com/uc?export=view&id=1IwWo_KmqZ_DSPiM1hf-7INmrzxl7VNye" width="30" height="30" class="penis_icon">
                                    {{ post.comments.count }} comentario{{ post.comments.count|pluralize }}

                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/view_profile.html
<!DOCTYPE html>
{% extends 'main.html' %}

{% block serach_block %}
{% endblock %}

{% block body_block%}



<div class="jumbotron main_wrapper_jumbotron">
    <div class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="col-lg-6 col-sm-12">
                    <div>
                        <div style="width: 300px; height: 300px">
                            <img src="{{ user.profiles.profile_pic.url }}" style="max-height: 280px; width:100%;max-width:268px; object-fit: cover">
                        </div>

                    </div>
                </div>
                <div class="col-lg-6 col-sm-12">

                    <div>
                        <h5>username: {{ user.username }}</h5>
                        <p>primer nombre: {{ user.first_name }}</p>
                        <p>apellido: {{ user.last_name }}</p>
                        <p>email: {{ user.email }}</p>
                        <p>descripcion: {{ user.profiles.description }}</p>
                        <p>genero: {{ user.profiles.gender }}</p>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}