meex/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('tip.urls', namespace='tips')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tip/urls.py
from django.conf.urls import url
from tip import views


app_name = 'tips'

urlpatterns = [
    url(r'^$', views.tips_list_search, name='list'),
    url(r'^create_tip/$', views.crate_tip, name='create_tip'),
    url(r'^reglas/$', views.reglas_view, name='reglas'),
    url('thankyou/', views.request_services, name='gracias'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserTips.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),

    # url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^tip/(?P<pk>\d+)/edit/$', views.TipUpdateView.as_view(), name='tip_edit'),
    url(r'^tip/(?P<pk>\d+)/remove/$', views.TipDeleteView.as_view(), name='tip_remove'),

    url(r'^tip/(?P<pk>\d+)$', views.tip_details, name='tip_detail'),
    url(r'^like/$', views.like_tip, name='like_tip'),
    url(r'^down/$', views.down_tip, name='down_tip'),
    url(r'^warning', views.CreateProfileBeforeSearch.as_view(), name='createprofilebeforeview'),

]

tip/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class MakeTip(models.Model):
    author = models.ForeignKey(User, related_name='tips', on_delete=models.CASCADE)
    title = models.CharField(max_length=63)
    post_pic = models.FileField(upload_to='media', blank=True, help_text='Selecciona video')
    creativity = models.IntegerField(default=0, null=True)
    sexy = models.IntegerField(default=0, null=True)
    quality = models.IntegerField(default=0, null=True)
    outfit = models.IntegerField(default=0, null=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def total_creativity(self):
        return self.creativity

    def total_sexy(self):
        return self.sexy

    def total_quality(self):
        return self.quality

    def total_outfit(self):
        return self.outfit


    # def post_info_summary(self):
    #     len_info = len(self.info)
    #     if len_info > 480:
    #         return self.info[:480]+' . . . .continue'
    #     else:
    #         return self.info

    def get_absolute_url(self):
        return reverse('tips:tip_detail', kwargs={'pk': self.pk})


class LikeUserList(models.Model):
    post = models.ForeignKey(MakeTip, related_name='members', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class DownVoteUserList(models.Model):
    post = models.ForeignKey(MakeTip, related_name='members_down', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

tip/forms.py
from django import forms
from .models import MakeTip
from django.forms import Textarea, TextInput, ImageField


class MakePostForm(forms.ModelForm):
    creativity = forms.IntegerField(required=False)
    sexy = forms.IntegerField(required=False)
    quality = forms.IntegerField(required=False)
    outfit = forms.IntegerField(required=False)
    post_pic = forms.FileField(required=True)

    class Meta:
        model = MakeTip
        fields = ['post_pic', 'title', 'creativity', 'sexy', 'quality', 'outfit']
        labels = {
            'post_pic': 'Selecciona video'
        }

        widgets = {
            'title': TextInput(attrs={'class': 'form-control'})
        }

tip/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, DeleteView, UpdateView, ListView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .forms import MakePostForm
from .models import MakeTip, LikeUserList, DownVoteUserList
# from comments.models import Comment
from django.db.models import Q
from accounts.models import PointsUserList, Profile
from django.contrib.auth import get_user_model
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count



User = get_user_model()


@login_required
def crate_tip(request):
    form = MakePostForm()

    if request.method == "POST":
        form = MakePostForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            user_tip = form.save(commit=False)
            user_tip.author = request.user
            form.save(commit=True)
            return redirect('tips:gracias')
        else:
            form = MakePostForm()

    return render(request, 'tip/maketip_form.html', {'form': form})



@login_required
def reglas_view(request):
    return render(request, 'tip/reglas.html')


@login_required
def tip_details(request, pk):
    post = get_object_or_404(MakeTip, pk=pk)
    is_liked = False
    is_down = False

    if DownVoteUserList.objects.filter(user=request.user, post=post.pk):
        is_down = True

    if LikeUserList.objects.filter(user=request.user, post=post.pk):
        is_liked = True
    context = {
        'post': post,
        # 'is_down': is_down,
        # 'is_liked': is_liked,
        # 'total_likes': post.total_likes(),
        # 'comment_list': Comment.objects.all().order_by('-created_date')
    }
    return render(request, 'tip/tip_detail.html', context)


@login_required
def like_tip(request):
    all_tipsx = MakeTip.objects.filter(author__exact=request.user)
    pksx = MakeTip.objects.filter(author__exact=request.user).values_list('id', flat=True)

    def appendTest(x):
        theList = []
        for i in x:
            theList.append(i)
        return theList

    to_be_deleted = []
    spp = appendTest(pksx)
    while spp:
        s2 = all_tipsx.get(pk=spp[-1])
        s3 = s2.total_down_votes()
        if s3 >= 105:
            to_be_deleted.append(s2.pk)
        spp.pop()
    for x in to_be_deleted:
        MakeTip.objects.filter(author__exact=request.user).get(pk=x).delete()

    is_liked = False
    tip = get_object_or_404(MakeTip, id=request.POST.get('post_id'))
    membership = LikeUserList.objects.filter(user=request.user, post=tip.pk)
    if membership:
        membership.delete()
        is_liked = False

    else:
        LikeUserList.objects.create(user=request.user, post=tip)
        is_liked = True
    return redirect(tip.get_absolute_url())


@login_required
def down_tip(request):
    is_down = False
    tip = get_object_or_404(MakeTip, id=request.POST.get('post_id'))
    membership = DownVoteUserList.objects.filter(user=request.user, post=tip.pk)
    if membership:
        membership.delete()
        is_down = False

    else:
        DownVoteUserList.objects.create(user=request.user, post=tip)
        is_down = True
    return redirect(tip.get_absolute_url())


class TipUpdateView(UpdateView, LoginRequiredMixin):
    form_class = MakePostForm
    success_url = reverse_lazy('tips:list')
    model = MakeTip


class TipDeleteView(DeleteView, LoginRequiredMixin):
    model = MakeTip
    success_url = reverse_lazy('tips:list')


class UserTips(ListView, LoginRequiredMixin):

    context_object_name = 'post_list'
    model = MakeTip
    template_name = 'tip/user_tip_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('tips').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.tips.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


def tips_list_search(request):
    notificaciones = 'none'
    if request.user.is_anonymous:
        pass

    queryset_list = '?'
    if request.method == 'GET':
        sku = request.GET.get('populares')
        sku2 = request.GET.get('comentadas')
        sku3 = request.GET.get('recientes')

        if sku:
            queryset_list = MakeTip.objects.annotate(like_count=Count('likes')).order_by('-like_count')
        elif sku2:
            queryset_list = MakeTip.objects.annotate(comment_count=Count('comments')).order_by('-comment_count')
        else:
            queryset_list = MakeTip.objects.all().order_by('-created_date')

    query = request.GET.get('q')
    if query is not None:
        queryset_list = queryset_list.filter(Q(title__icontains=query) | Q(info__icontains=query))

    paginator = Paginator(queryset_list, 36)    # Show 25 contacts per page

    page = request.GET.get('page')
    queryset = paginator.get_page(page)

    context = {
        'notifications_list': notificaciones,
        "post_list": queryset
    }
    return render(request, 'tip/tip_list.html', context)


class CreateProfileBeforeSearch(TemplateView, LoginRequiredMixin):
    template_name = 'tip/create_a_profile.html'


def request_services(request):
    return render(request, 'tip/gracias.html')

tip/templates/tip/_tip.html
<!DOCTYPE html>
<div class="jumbotron main_wrapper_jumbotron">

<div class="container">

    <div class="card text-white bg-light mb-3">
    {% if post.post_pic %}

        <video class="embed-responsive embed-responsive-16by9" width="320" height="240" controls>
          <source src="{{ post.post_pic.url }}" type="video/mp4">
          Your browser does not support the video tag.
        </video>

    {% endif %}
        <div class="card-body">

            <p class="text-center" style="color: black">{{ post.title }}</p>
            <p class="card-title"><a href="{% url 'tips:for_user' username=post.author.username %}" style="color: #e8c600">@{{ post.author.username }}</a></p>
            <p class="card-text" style="color: #e8c600">Publicado en: {{post.created_date|date:"m /d/ Y"}}</p>

            {% if user.is_authenticated and post.author == user %}
                <br>
                    {% if user.is_authenticated and post.author == user %}
                <div class="prize" style="padding: 10px; border-radius: 10px">
                        <h5 id="cr">Creatividad: {{ post.creativity }}/5</h5>
                        <h5 id="sn">Sensualidad/sexi: {{ post.sexy }}/7</h5>
                        <h5 id="cl">Calidad del video/claridad: {{ post.quality }}/5</h5>
                        <h5 id="at">Atuendo/outfit: {{ post.outfit }}/6</h5>
                        <h5>Total: <span id="tt"></span>/23</h5>
                    </div>
                        <a href="{% url 'tips:tip_remove' pk=post.pk%}" class="btn btn-outline-danger" style="margin: 5px">Remover</a>
                    {% endif %}
            {% endif %}
        </div>



    </div>
</div>


</div>
<script>
    let r = {{ post.creativity }}+ {{ post.sexy }}+{{ post.quality }}+ {{ post.outfit }};
    let g = document.getElementById('tt');
    g.textContent = r;
</script>

tip/templates/tip/create_a_profile.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% block body_block %}
<div class="jumbotron main_wrapper_jumbotron">
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <p>Necesitas crear un perfil antes de buscar usuarios/commentar/oh dar parada</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tip/templates/tip/gracias.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% block body_block %}
        <div class="jumbotron jumbotron-fluid">
  <div class="container">

<div class="alert alert-success" role="alert">
        <p>Gracias por enviar tu video</p>
</div>

<div class="alert alert-primary" role="alert">
      <p>Pronto se calificará tu video y podras mirar tu puntuación. Favor de esperar unos 30 minutos para poder ver la puntuación.</p>
</div>

<div class="alert alert-primary" role="alert">
      <p>Tendrá una puntuación de zero si todavia no se ha calificado. Máximo de 23 puntos en total.</p>
</div>


      <a class="navbar-brand" href="{% url 'tips:list'%}">Regresar a menú principal</a>

  </div>
</div>




{% endblock %}

tip/templates/tip/maketip_confirm_delete.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}
    <div class="jumbotron main_wrapper_jumbotron">
        <div class="container">
        <div class="jumbotron">
            <div class="d-flex justify-content-center">

  <form method="post">

      {% csrf_token %}
      <p>¿Estás segura que quieres borrar?</p>
      <h6>{{ object }}</h6>

<video class="embed-responsive embed-responsive-16by9" width="320" height="240" controls>
  <source src="{{ object.post_pic.url }}" type="video/mp4">
  Your browser does not support the video tag.
</video>

      <button type="submit" class="btn btn-danger" style="margin: 5px">Borrar</button>

  </form>
            </div>
        </div>
        </div>
</div>
{% endblock %}

tip/templates/tip/maketip_form.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% load bootstrap4 %}
{% block body_block %}

{% block serach_block %}
{% endblock %}




    <div class="container">
            <div class="d-flex justify-content-center">

                <form action="{% url 'tips:create_tip'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div>

                    <a class="nav-link" href="{% url 'tips:reglas'%}" style="  background-color: rgba(218,61,48,0.77);color: white;padding: 1em 1.5em;text-decoration: none;border-radius: 5px;margin: 5px;text-transform: uppercase;">Reglas & Puntuación</a>

                        <p style="color: white">Nombre: {{ form.title }}</p>


                            <label style="color: white">Imagen</label>
                        <p style="color: green">Presiona el botton "Choose file" de abajo para enviar video</p>
        {#                    <input type="file" accept="image/*" onchange="loadFile(event)" value="{{ form.post_pic }}">#}
                            <p onchange="loadFile(event)">{{ form.post_pic }}</p>
                    </div>
                    <div class="form-row">

                    <video id="output" width="320" height="240" controls>
                      <source type="video/mp4">
                      Your browser does not support the video tag.
                    </video>
                    </div>

                    <button type="submit" class="btn btn-primary" style="margin: 10px" onclick="showDiv()">Publicar</button>


                </form>
            </div>


        <div class="alert alert-success" role="alert" style="margin: 10px; display: none" id="loadingGif">
    <h4>Enviando Video........</h4>
</div>

        <div class="alert alert-danger" role="alert" style="margin: 10px">
    <h4>Los videos submitidos se borraran automaticamente al final del concurso.</h4>
</div>

    </div>



<script>
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
  };

      function showDiv() {
  document.getElementById('loadingGif').style.display = "block";
  setTimeout(function() {
    document.getElementById('loadingGif').style.display = "none";
  },200000);

}

</script>

{% endblock %}

tip/templates/tip/reglas.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% block body_block %}
        <div class="jumbotron jumbotron-fluid">
  <div class="container">

        <div class="alert alert-primary" role="alert">
      <h5>Entre más videos envies mayor la posibilidad de ganar!</h5>
        </div>

        <div class="alert alert-success" role="alert">
      <h5>Cómo ganar?</h5>
            <p>Video con mayor puntuación</p>
            <p>Al final si varios videos tienen las misma puntuación se elegirá al azar</p>
        </div>

      <h4>Requisitos</h4>
      <p class="lead">El video tiene que tener una duración de al menos 3 minutos o más</p>
      <p class="lead">Solo mayores de +12 años</p>
      <p class="lead">Solo se permite usar shorts, leggings, falda, traje de baño o ropa interior</p>
      <p class="lead">No tienes que enseñar la cara si asi lo deseas, no afecta tu puntuación</p>

      <h4>Cómo se califica el video</h4>
      <p class="lead">Creatividad - Máximo de 5 puntos</p>
      <p class="lead">Sensualidad/sexi - Máximo de 7 puntos</p>
      <p class="lead">Calidad del video/claridad - Máximo de 5 puntos</p>

      <h4>Calificación de atuendo/outfit</h4>
      <p class="lead">Shorts - Máximo de 5 puntos</p>
      <p class="lead">Leggings - Máximo de 5 puntos</p>
      <p class="lead">Falda - Máximo de 6 puntos</p>
      <p class="lead">Traje de baño/ropa interior - Máximo de 6 puntos</p>

        <div class="alert alert-success" role="alert">
      <h4>Forma de pago</h4>
      <p class="lead">Si eres la ganadora de algunos de los 3 premios se te contactará por Instagram o por correo elctronico para hacer el pago através de Zoom.com</p>
        </div>


  </div>
</div>




{% endblock %}

tip/templates/tip/tip_detail.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}
    {% include "tip/_tip.html" %}
{% endblock %}

tip/templates/tip/tip_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block body_block %}

<div class="prize">
  <div class="container">
      <h1 class="display-4"> Concurso Internacional Twerk 2020</h1>
    <h2>1 lugar 20,000 Pesos</h2>
    <h2>2 lugar 12,000 Pesos</h2>
    <h2>3 lugar 10,000 Pesos</h2>
    <p class="lead">Ganadoras se elegirán el 25 de Junio 2020</p>
      <p class="lead">Felicidades a Yadira P, Oriana O y a Sofia C que fueron las ganadoras del concurso del 2019</p>
  </div>
</div>

<div class="jumbotron main_wrapper_jumbotron">

{#    <div class="d-flex justify-content-center">#}
{##}
{#        <form method="GET" action="{% url 'tips:list'%}" class="form-inline">#}
{#            {% csrf_token %}#}
{#            <div class="input-group input-group-lg">#}
{#                <div class="input-group-prepend">#}
{#                    <span class="input-group-text" id="inputGroup-sizing-lg">Buscar Tips</span>#}
{#                </div>#}
{#                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="q">#}
{#                <button type="submit" class="btn btn-dark">GO</button>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}


{#    <div class="d-flex flex-row bd-highlight mb-3">#}
{#        <div class="p-2 bd-highlight">#}
{#            <form method="get" href="{% url 'tips:list'%}">#}
{#                {% csrf_token %}#}
{#                <button type="submit" name="populares" value="popular" class="btn btn-light btn-sm">Top Paradas</button>#}
{#            </form>#}
{#        </div>#}
{#        <div class="p-2 bd-highlight">#}
{#            <form method="get" href="{% url 'tips:list'%}">#}
{#                {% csrf_token %}#}
{#                <button type="submit" name="comentadas" value="comment" class="btn btn-light btn-sm">Top Comentadas</button>#}
{#            </form>#}
{#        </div>#}
{#        <div class="p-2 bd-highlight">#}
{#            <form method="get" href="{% url 'tips:list'%}">#}
{#                {% csrf_token %}#}
{#                <button type="submit" name="recientes" value="recientes" class="btn btn-light btn-sm">Recientes</button>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}


    <div class="row">
        {% for post in post_list %}
            <div class="col-md-4">
                <div>
                    <div class="card text-white bg-light mb-3">
                        {% if post.post_pic %}
                            <a href="{% url 'tips:tip_detail' pk=post.id %}">
                            <div class="card-body">
<video class="embed-responsive embed-responsive-16by9" width="320" height="240" controls>
  <source src="{{ post.post_pic.url }}" type="video/mp4">
  Your browser does not support the video tag.
</video>
                                <p class="card-text prize" style="text-align: center;"><a href="{% url 'tips:tip_detail' pk=post.id %}" style="color: white">{{ post.title }}</a></p>
                                <p class="card-text"><a href="{% url 'tips:for_user' username=post.author.username %}" style="color: #e2c200">@{{ post.author.username }}</a></p>
                            </div>
                                            </a>

                        {% else %}
                            <div class="card-body">
                                <p class="text-center"><a href="{% url 'tips:tip_detail' pk=post.id %}">{{ post.title }}</a></p>
                                <p class="card-text">{{ post.post_info_summary }}</p>
                                <p class="card-text"><a href="{% url 'tips:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>

                            </div>

                        {% endif %}
                    </div>
                </div>


            </div>

        {% endfor %}
    </div>

    <div class="d-flex justify-content-center">

        <div class="pagination">
            {% if post_list.has_other_pages %}
                {% if post_list.has_previous %}
                  <a href="?page={{ post_list.previous_page_number }}" class="pagination_numbers">&laquo;</a>
                {% else %}
                  <div class="disabled pagination_numbers"><span>&laquo;</span></div>
                {% endif %}
                {% for i in post_list.paginator.page_range %}
                  {% if post_list.number == i %}
                    <div class="pagination_numbers"><span> {{ i }} </span></div>
                  {% else %}
                    <a href="?page={{ i }}" class="pagination_numbers">{{ i }}</a>
                  {% endif %}
                {% endfor %}
                {% if post_list.has_next %}
                  <a href="?page={{ post_list.next_page_number }}" class="pagination_numbers">&raquo;</a>
                {% else %}
                  <div class="disabled pagination_numbers"><span>&raquo;</span></div>
                {% endif %}
            {% endif %}
        </div>

    </div>
</div>
{% endblock %}

tip/templates/tip/user_tip_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}

<div class="jumbotron main_wrapper_jumbotron">
    <div class="row">
        {% if post_list %}
            {% for post in post_list %}
            <div class="col-lg-4">
                <div>
                      <div class="card text-white bg-light mb-3">
                            {% if post.post_pic %}
{#                                <img class="card-img-top silvano" src="{{ post.post_pic.url }}" alt="Card image cap">#}

                                    <video class="embed-responsive embed-responsive-16by9" width="320" height="240" controls>
                                      <source src="{{ post.post_pic.url }}" type="video/mp4">
                                      Your browser does not support the video tag.
                                    </video>
                                <div class="card-body">
                                    <p class="text-center prize"><a href="{% url 'tips:tip_detail' pk=post.id %}" style="color: white">{{ post.title }}</a></p>
                                    <p class="card-text" style="color: #e6be00">Publicado en: {{post.created_date|date:"d /m/ Y"}}</p>
                                    <div class="card-text">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                        {% if user.is_authenticated and post.author == user %}
                                            <a href="{% url 'tips:tip_remove' pk=post.pk%}" class="btn btn-outline-danger">Borrar</a>
                                            <a href="{% url 'tips:tip_detail' pk=post.id %}" class="btn btn-outline-info">Puntuación</a>
{#                                            <a href="{% url 'tips:tip_edit' pk=post.pk%}" class="btn btn-outline-info">Editar</a>#}
                                        {% endif %}
                                        </div>
                                    </div>
                                    <br>
{#                                    <p class="card-text"><a href="{% url 'comments:add_comment_to_post' pk=post.pk %}" class="btn btn-light">Agregar Comentario</a></p>#}
                                </div>

{#                                <div class="card-footer text-muted">#}
{#                                    {{ post.likes.count }} <img src="http://drive.google.com/uc?export=view&id=1iyEMUO63gvEuYu1zLYWi3SpUzCbU6tWs" width="30" height="30" class="penis_icon">#}
{#                                    {{ post.down_votes.count }} <img src="http://drive.google.com/uc?export=view&id=1IwWo_KmqZ_DSPiM1hf-7INmrzxl7VNye" width="30" height="30" class="penis_icon">#}
{#                                    {{ post.comments.count }} comentario{{ post.comments.count|pluralize }}#}
{#                                </div>#}

                            {% else %}
                                <div class="card-body">
                                    <p class="text-center"><a href="{% url 'tips:tip_detail' pk=post.id %}">{{ post.title }}</a></p>
                                    <p class="card-text">{{ post.post_info_summary }}</p>
                                    <p class="card-text">Publicado en: {{post.created_date|date:"D M Y"}}</p>
                                    <div class="card-text">
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                        {% if user.is_authenticated and post.author == user %}
                                            <a href="{% url 'tips:tip_remove' pk=post.pk%}" class="btn btn-outline-danger">Remover</a>
{#                                            <a href="{% url 'tips:tip_edit' pk=post.pk%}" class="btn btn-outline-info">Editar</a>#}
                                        {% endif %}
                                        </div>
                                    </div>
                                    <br>
{#                                    <p class="card-text"><a href="{% url 'comments:add_comment_to_post' pk=post.pk %}" class="btn btn-light">Agregar Comentario</a></p>#}
                                </div>

{#                                <div class="card-footer text-muted">#}
{#                                    {{ post.likes.count }} <img src="http://drive.google.com/uc?export=view&id=1iyEMUO63gvEuYu1zLYWi3SpUzCbU6tWs" width="30" height="30" class="penis_icon">#}
{#                                    {{ post.down_votes.count }} <img src="http://drive.google.com/uc?export=view&id=1IwWo_KmqZ_DSPiM1hf-7INmrzxl7VNye" width="30" height="30" class="penis_icon">#}
{#                                    {{ post.comments.count }} comentario{{ post.comments.count|pluralize }}#}
{#                                </div>#}

                        {% endif %}
                        </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="container">
                <div class="jumbotron">
                    <div align="center">
                        <p>No Videos</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}