accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'

urlpatterns = [
    url(r'^registration/$', views.create_user_form, name='registration'),
    url(r'^$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^point/$', views.point_crown, name='point_crown'),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),

]

meex/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('tip.urls', namespace='tips')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tip/urls.py
from django.conf.urls import url
from tip import views


app_name = 'tips'

urlpatterns = [
    url(r'^$', views.tips_list_search, name='list'),
    url(r'^create_tip/$', views.crate_tip, name='create_tip'),
    url(r'^reglas/$', views.reglas_view, name='reglas'),
    url('thankyou/', views.request_services, name='gracias'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserTips.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),

    # url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^tip/(?P<pk>\d+)/edit/$', views.TipUpdateView.as_view(), name='tip_edit'),
    url(r'^tip/(?P<pk>\d+)/remove/$', views.TipDeleteView.as_view(), name='tip_remove'),

    url(r'^tip/(?P<pk>\d+)$', views.tip_details, name='tip_detail'),
    url(r'^like/$', views.like_tip, name='like_tip'),
    url(r'^down/$', views.down_tip, name='down_tip'),
    url(r'^warning', views.CreateProfileBeforeSearch.as_view(), name='createprofilebeforeview'),

]

templates/main.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}

<html lang="en">
<head>
    <meta charset="UTF-8" content="width=device-width, initial-scale=1" name="viewport" >
    <title>Twerk</title>
    <link rel="stylesheet" href="{% static 'css/css_style.css' %}"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body class="main_wrapper_jumbotron">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% if user.is_authenticated %}

    <a class="navbar-brand" href="{% url 'tips:list'%}" style="color: gold">
    TWERK
    </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbarXs">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="collapsingNavbarXs">
            <ul class="navbar-nav mr-auto">


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tips:create_tip'%}" >Enviar Video</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tips:reglas'%}" >Reglas/Requisitos</a>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.profiles %}
                            {% if request.user.profiles.rey_reina %}
                                {% else %}
{#                                <a class="dropdown-item" href="{% url 'tips:get_crown'%}">Corona</a>#}
                            {% endif %}
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'tips:for_user' username=request.user.username%}">Mis videos</a>
{#                    <a class="dropdown-item" href="{% url 'friends:my_list_friend' username=request.user %}">Amigos</a>#}
                    </div>
                </li>

            {% if user.profiles %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Perfil
                    </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:viewprofile' %}">Ver Perfil</a>
                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">Editar Perfil</a>
                    <a class="dropdown-item" href="{% url 'accounts:confirm-deactivate' %}">Desactivar</a>
                </div>
                </li>

                {% if request.user.profiles.rey_reina %}

                    {% if request.user.profiles.gender == 'hombre' %}
                        <li class="nav-item">
                            <img src="http://drive.google.com/uc?export=view&id=1jPQLUooJkbUhxCVP7hLaaAEgdqAx_mYP" width="38" height="38" alt="logo">
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <img src="http://drive.google.com/uc?export=view&id=16fqZqtD6u2jLeRQYVk7cj_APWgNGMezU" width="38" height="38" alt="">
                        </li>
                    {% endif %}
                {% endif %}

            {% else %}
                <li class="nav-item">
{#                    <a class="nav-link" href="{% url 'accounts:createprofile'%}">Crear perfil</a>#}
                </li>
            {% endif %}
            </ul>
                    <a class="nav-link" href="{% url 'logout'%}" >Cerrar Sesión</a>

{#            {% block serach_block %}#}
{#                <form method="GET" action="{% url 'accounts:list'%}" class="form-inline">#}
{#                    {% csrf_token %}#}
{#                    <input class="form-control mr-sm-2" type="text" placeholder="Buscar usuarios" aria-label="Search" name="q">#}
{#                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>#}
{#                 </form>#}
{#            {% endblock %}#}
        </div>
    {% else %}
            <a class="nav-link" href="{% url 'login'%}">Iniciar Sesión</a>
            <a class="nav-link" href="{% url 'accounts:registration'%}">Registrarse</a>
    {% endif %}
</nav>



{% block body_block %}

{% endblock %}



</body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>